### ISSUE TITLE
Sync failed

### ISSUE THREAD

**Issue by DL3RTL** [magicbug/CloudlogCAT#1]
Omnirig connected and works fine.
API Keay from website generated and entered.
URL also filled in.

Error message: Cloundlog Synced: Feiled, check URL/API

Cloudlog runs on a webserver with https and the main folder is htaccess protected with a password.

**Comment by magicbug** [comment]
You answered your own question, the fact you have http basic Auth enabled & the application doesn't support taking those details

**Comment by DL3RTL** [comment]
Good morning any thanks for your fast replies.

As far as I understood Cloudlog is built for instalation on a public server. Otherwise it would not be a accessable on the cloud without a speciel infrastructure at home like an own webserver, a firewall, a VPN etc.

Without auth everyone not only can see all my logs but also the content of the comment field. There may be private remarks.

In addition I wanted to prevent people from playing with the login.

For that reason I choosed the beasic auth that works pretty well.

Maybe I misunderstood something and you know a better way of protection or a better place for installation.

**Comment by magicbug** [comment]
Not sure what's being misunderstood, wiki documentation doesn't talk about HTTP Basic Auth, that's completely a choice for the user but not something that CloudlogCAT currently supports.

There's no system for a user to "sign up" on a Cloudlog instance & I've not seen anyone "playing" with it personally and I have a few hundred hosted.

However, for this to work you'd need to add some extra fields inside the desktop application to deal with it.
