### ISSUE TITLE
Can't connect to Cloudlog 

### ISSUE THREAD

**Issue by myhobby2** [magicbug/CloudlogCAT#11]
Used to work last week but had to re-install everything after a windows registry issue. Cloudlog is working and WSJTX interfaces to cloudlog via Cloudlog Aurora. No issues there. 

CloudlogCat Rig1 is set up correctly and shows the correct freq and updates this also when changing frequencies. 
Cloudlog API created and url in my case (http://192.168.1.40/cloudlog/) is the correct URL. API-key is copied from Cloudlog in CloudlogCat. But I still have Cloudlog synced Failed, check URL/API

Running currently Windows 10, build 19045.5247, version 22H2

**Comment by magicbug** [comment]
Try removing the trialing / on the cloudlog part

**Comment by myhobby2** [comment]
Just changed the url to http://192.168.1.40/cloudlog  and created a new APIKEY. Still no success.
