### ISSUE TITLE
Frequency not passed through

### ISSUE THREAD

**Issue by TriBallscom** [magicbug/CloudlogCAT#2]
Installed omnirig and CloudlogCAT but noticed that CliudlogCAT is not passing through the frequency.
Omnirig is passing through the frequency in other applications so thare is not the problem.

**Comment by magicbug** [comment]
It's due to the fact I believe I use the returned variable Freq instead of the vfo a

**Comment by TriBallscom** [comment]
Can I fix it? 
Cloudlog does not use the frequency now, that's a bit annoying

**Comment by magicbug** [comment]
Can you try this version https://github.com/magicbug/CloudlogCAT/releases/download/1.8/CloudlogCAT.Test.Release.ICOM.zip not promising its fixed but perhaps

**Comment by TriBallscom** [comment]
Sorry, was away for a couple of days.
it seems that CloudlogCAT doe sync with the Cloudlog API but Cloudlog keeps telling me: "No CAT Interfaced radios found."
CloudlogCAT shows the correct frequency and shows that it syncs with Cloudlog.

**Comment by magicbug** [comment]
Weird, is anything showing in the cat table in the database? if the website is saying no radios that suggests somethings happening on the website end

**Comment by TriBallscom** [comment]
The cat table is empty.
What I did was install the new test version of CloudlogCAT and when I noticed in Cloudlog that the radio was not updating I deleted that and hoped that it would be populated again. 
The CloudlogCAT interface tells me tat it connects to the API and synchronizes, if I change the API url for test purposes it fails so I have to assume the connection is working.

**Comment by magicbug** [comment]
I can only really recommend checking the server error log see if it's moaning.

**Comment by TriBallscom** [comment]
Oke, checked the log and did some tests.
There are no errors and Cloudlogcat gives a "synced" message but Cloudlog keeps telling me that there are no CAT interface radios are found. I installed CloudCat 1.3 again and that registered a radio in CloudLog but does not show the frequency. 
The CloudlogCat ICOM test version shows the frequency in the interface just does not populate Cloudlog.
