### ISSUE TITLE
Timezones other than GMT fail to sync properly

### ISSUE THREAD

**Issue by ofadam** [magicbug/CloudlogCAT#7]
As mentioned in the other issues linked below, it seems that those not in GMT may have trouble getting CloudlogCAT to successfully sync with Cloudlog since this commit: https://github.com/magicbug/Cloudlog/commit/b18e1013f3a121d07c7b4f97c5f401b7ba64fca0

https://github.com/magicbug/Cloudlog/issues/1240

https://github.com/magicbug/Cloudlog/issues/1236

I've rolled back the Cat.php file to a previous version to regain that sync ability, but wanted to flag in case it was an easy client fix in CloudlogCAT.

**Comment by magicbug** [comment]
Plan to address that today.

**Comment by magicbug** [comment]
Changed some code within Cloudlog to hopefully fix this it now sets the time on the query to UTC rather than server time.

CloudlogCAT Always uploads in UTC.
